# Can replace any mcp executed through `uvx` or similar
# Doesn't set CMD so you have to pass the command to execute in the
# container when running it or in the compose file.

# Builder
FROM ghcr.io/astral-sh/uv:python3.12-slim
WORKDIR /app

ARG MCP_PACKAGE

ENV UV_TOOL_BIN_DIR=/usr/local/bin
ENV UV_CACHE_DIR=/tmp/uv-cache

RUN uv tool install ${MCP_PACKAGE} \
    --from ${MCP_PACKAGE}

USER 1000
CMD ${MCP_PACKAGE}
