# Can replace any mcp executed through `npx` or similar
# Doesn't set CMD so you have to pass the command to execute in the
# container when running it or in the compose file.

# Builder
FROM node:24 AS builder
WORKDIR /app

ARG MCP_PACKAGE

RUN npm install $MCP_PACKAGE

# Runtime
FROM node:24-alpine
WORKDIR /app

ARG MCP_PACKAGE

COPY --from=builder \
    /app/node_modules \
    /app/node_modules

ENV NODE_PATH=/app/node_modules
WORKDIR /app/node_modules/.bin
